### ISSUE TITLE
Get to know crowdin

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer-i18n#1]
https://crowdin.com/

Complete tutorials, check out how napari project implemented:
- https://crowdin.com/project/napari 
- https://github.com/Napari/napari

**Comment by comradekingu** [comment]
@lassoan Hoping to see this project move to Weblate now that the results are in.
in 9 months, there are 6 translations, all below 13% coverage.
There is every reason to stay clear of Crowdin beyond that, and you will find quality always suffers on that platform.

Napari isn't doing continuous translations, and is wasting entire languages because of how Crowdin is set up.

**Comment by lassoan** [comment]
We created the crowdin project months ago but only started the translation about 2 weeks ago. We haven't encountered any major issues but if you have some specifics to share then please tell us more.

**Comment by comradekingu** [comment]
It is impossible to see more languages at once, or span large amounts of strings. The terms and conditions are awful, trying to get anything done takes longer than it has to, and translations are most often held up in a voting system that disadvantages smaller efforts. Seeing as how effort is hard to come by on Crowdin this issue is exacerbated by picking out of the time available from the few translators that are good, a lot of drive-by translators.
To arrive at coverage by lots of small independent contributions further ensures no consistency will be had.
There are no feedback-loops up to the project, or by crediting translators. There actually is very little transparency even on the platform without having an account.
Crowdin can't even get the locales right, which means translators are baited into starting translations that actively undermine good efforts or existing resources.
The company behind the only-as-a-service product is not honest, and continually misrepresents its PR efforts.
The offering for libre sofware isn't even that, as takes away rights to commercialize the project without negotiating enterprise planning.
Especially when similar software uses Weblate, I don't understand why a libre software project opts for the lesser option.

**Comment by lassoan** [comment]
Thank you for your detailed response.

Many of the advantages that you described above were not very clear (probably because I still know very little about Crowdin and Weblate), but I agree that Weblate could be a better fit for Slicer.

In general, Weblate has many more features and more customizable. We already ran into some annoying limitations of crowdin that Weblate does not seem to suffer from, such as projects are only viewable after user registration (even if public), glossary terms are only editable by managers, there don't seem to be discussions for specific translations, access control roles are very coarse (manager/proofreader/admin), github integration is limited, REST API is quite limited, downloading of translations is complicated, etc. It may be important for custom applications that Weblate is open-source and can be run self-hosted (just in case custom applications want to adopt Slicer core's translation infrastructure). It seems that Weblate can also be used for translating documentation (see for example the [Godot project](https://hosted.weblate.org/translate/godot-engine/godot-docs/it/?checksum=b1db81fdade3ec02&sort_by=-priority,position#machinery) ([translated documentation page example](https://docs.godotengine.org/es/stable/)). It is nice that translator's work is attributed (it is easier to give credits to contributors).

In addition to these, Weblate offers free hosting for open-source projects with less limitations than crowdin's free plan. For example, Weblate supports multiple branches, so we would not need to resort to workarounds that we had to use with crowdin (putting all branches in a subfolders in a directory tree in a single git branch). 

> Especially when similar software uses Weblate, I don't understand why a libre software project opts for the lesser option.

We were in contact with [napari](https://napari.org/) folks. They are funded by CZI - the same way as our translation effort. There are many similarities between the projects, so we figured that if crowdin works for them then it should work for us, too.

-----

@pieper @jcfr @spujol Please have a look at [Weblate](https://weblate.org/). I think we should seriously consider switching. The already translated .ts files can be transferred easily.

**Comment by pieper** [comment]
Interesting discussion, thanks for bringing this to our attention @comradekingu.

**Comment by lassoan** [comment]
@comradekingu can you help with a few more questions?
- Can you confirm that the Slicer project would qualify for a free plan?
- If we wanted to use Weblate to translate the Slicer User Manual as well then we would probably need more than 10k strings. Are there examples that limits of the plan are relaxed for a large open-source project (or we would need to switch to a paid plan if we exceed any of the limits)?
- Could you help with how to organize translation files for multiple languages and software versions (branches) and how to transfer or existing .ts files to Weblate if we decide to switch?

**Comment by comradekingu** [comment]
Not on Hosted, because a FSF or OSI license is required.
I don't think there are hard limits.
Could try https://weblate.bubu1.eu/ or self-host.
I could maybe help, but then again I also limit myself to libre software,
and I don't understand this one well enough.
The text below is an argument I began making, but then gave up on.

>You further agree to
   use, reproduce, make derivative works of, display and distribute
   the Software in compliance with all applicable governmental laws,
   regulations and orders, including without limitation those relating
   to export and import control.

Don't know if this qualifies as libre.

>you accept and adhere to all of the terms and conditions of this
Software License;

(c) you preserve and maintain all applicable attributions, copyright
notices and licenses included in or applicable to the Software;

The license granted in this Software License includes without
   limitation the right to (i) incorporate the Software into
   proprietary programs (subject to any restrictions applicable to
   such programs),

**Comment by pieper** [comment]
@comradekingu there is more information about Slicer licensing in this thread and the links it contains:

https://discourse.slicer.org/t/apply-for-osi-open-source-license-status/17791/5

**Comment by lassoan** [comment]
If Slicer would not qualify for free hosting at weblate, then we would need to pay $1100 per year. This would not be prohibitive, but considering that we already started on Crowdin and they provide us free hosting, the scale could tip towards staying with Crowdin.

@pieper To get a definitive answer on this, could you try to create a non-commercial hosted project for Slicer at weblate? After you register you can create a new project here: https://hosted.weblate.org/hosting/

**Comment by lassoan** [comment]
This repository will be removed because we have too many repositories for this project already. The issue is moved to https://github.com/Slicer/SlicerLanguagePacks/issues/2
